[package]
name = "espi-service"
version = "0.1.0"
edition = "2021"
description = "eSPI embedded service implementation"
repository = "https://github.com/pop-project/embedded-services"
rust-version = "1.83"
license = "MIT"

[dependencies]
