
# cargo-vet audits file

[[audits.addr2line]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.24.2"

[[audits.aligned]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.4.2"

[[audits.aquamarine]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.6.0"

[[audits.as-slice]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.1"

[[audits.backtrace]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.3.75"

[[audits.block-device-driver]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.0"

[[audits.const-init]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.embedded-batteries]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.1"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries-async]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries-async]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries-async]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.1"

[[audits.embedded-fans]]
who = "Kurtis Dinelle <kdinelle@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-fans-async]]
who = "Kurtis Dinelle <kdinelle@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.0"
notes = "ODP crates are always trusted."

[[audits.embedded-sensors-hal]]
who = "Kurtis Dinelle <kdinelle@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-sensors-hal-async]]
who = "Kurtis Dinelle <kdinelle@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.3.0"
notes = "ODP crates are always trusted."

[[audits.futures-task]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.3.31"

[[audits.generator]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.8.5 -> 0.8.7"

[[audits.gimli]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.31.1"

[[audits.half]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
delta = "2.5.0 -> 2.6.0"
notes = "Big change seems to be a change in the repo URL, but both the old and new URL resolve to the same place so it looks like the author is still in control."

[[audits.include_dir]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.4"

[[audits.include_dir_macros]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.4"

[[audits.indexmap]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.9.0"

[[audits.itertools]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.10.5"

[[audits.itertools]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.11.0"
notes = "Used as a dependency for embassy-imxrt."

[[audits.libc]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.2.172"

[[audits.log]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.4.27 -> 0.4.28"

[[audits.matchers]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.1.0 -> 0.2.0"

[[audits.memchr]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "2.7.4"

[[audits.mimxrt633s-pac]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.4.0"

[[audits.mimxrt633s-pac]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.4.1"

[[audits.mimxrt633s-pac]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.5.0"

[[audits.mimxrt685s-pac]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.5.0"

[[audits.miniz_oxide]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.8.8"

[[audits.mutex-traits]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.1"

[[audits.nu-ansi-term]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.46.0 -> 0.50.1"

[[audits.object]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.36.7"

[[audits.portable-atomic]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.11.1"

[[audits.portable-atomic]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "1.11.1"

[[audits.rtt-target]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.6.1"

[[audits.serde_spanned]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.6.8"

[[audits.static_cell]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.1.1"

[[audits.static_cell]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "2.1.1"

[[audits.tokio]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "1.45.0"

[[audits.tokio-macros]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "2.5.0"

[[audits.toml]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.8.22"

[[audits.toml_datetime]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.6.9"

[[audits.toml_edit]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.22.26"

[[audits.tracing-attributes]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.1.28 -> 0.1.30"

[[audits.tracing-core]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.1.33 -> 0.1.34"

[[audits.tracing-log]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
delta = "0.1.3 -> 0.2.0"

[[audits.ufmt-write]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.uuid]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.17.0"

[[audits.windows-targets]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_aarch64_gnullvm]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_aarch64_msvc]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_i686_gnu]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.0"

[[audits.windows_i686_gnu]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_i686_gnullvm]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_i686_msvc]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_x86_64_gnu]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_x86_64_gnullvm]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_x86_64_msvc]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.winnow]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.10"

[[audits.zerocopy]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.8.26"

[[audits.zerocopy-derive]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.8.26"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2026-09-03"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2026-04-16"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2022-10-29"
end = "2026-09-03"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2026-09-03"

[[trusted.loom]]
criteria = "safe-to-deploy"
user-id = 6741 # Alice Ryhl (Darksonn)
start = "2021-04-12"
end = "2026-09-03"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2026-09-03"

[[trusted.paste]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-19"
end = "2026-09-03"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2026-09-03"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2026-09-03"

[[trusted.rustversion]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-08"
end = "2026-09-03"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2026-09-03"

[[trusted.scoped-tls]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-02-26"
end = "2026-09-03"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2026-09-03"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2026-09-03"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-09-03"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-09-03"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-09-03"

[[trusted.windows]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-01-15"
end = "2026-09-03"

[[trusted.windows-collections]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2025-02-06"
end = "2026-09-03"

[[trusted.windows-core]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-09-03"

[[trusted.windows-future]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2025-02-10"
end = "2026-09-03"

[[trusted.windows-implement]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-01-27"
end = "2026-09-03"

[[trusted.windows-interface]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-02-18"
end = "2026-09-03"

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-07-17"
end = "2026-09-03"

[[trusted.windows-numerics]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2023-05-15"
end = "2026-09-03"

[[trusted.windows-result]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-02-02"
end = "2026-09-03"

[[trusted.windows-strings]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-02-02"
end = "2026-09-03"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-09-03"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2026-09-03"

[[trusted.windows-threading]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2025-04-29"
end = "2026-09-03"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-09-03"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2026-09-03"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-09-03"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2026-09-03"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-09-03"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-09-03"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-09-03"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-09-03"
