[package]
name = "storage_bus"
version = "0.1.1"
edition = "2024"
description = "Storage Bus interfaces"
repository = "https://github.com/OpenDevicePartnership/embedded-services"
rust-version = "1.85"
license = "MIT"

[dependencies]
