[workspace]

[package]
name = "rt633-examples"
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.lints.rust]
warnings = "deny"

[lints]
workspace = true

[dependencies]
cortex-m = { version = "0.7.7", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = "0.7.3"
defmt = "0.3.6"
defmt-rtt = "0.4.0"
panic-probe = { version = "0.3.1", features = ["print-defmt"] }
embassy-imxrt = { git = "https://github.com/OpenDevicePartnership/embassy-imxrt", features = [
    "defmt",
    "time-driver-os-timer",
    "time",
    "mimxrt633s",
    "unstable-pac",
] }

embassy-sync = { version = "0.7.2", features = [
    "defmt",
] }
embassy-executor = { version = "0.9.0", features = [
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
] }
embassy-futures = "0.1.2"
embassy-time = { version = "0.5.0", features = [
    "defmt",
    "defmt-timestamp-uptime",
] }
embedded-hal-async = "1.0.0"
futures = { version = "0.3.30", default-features = false, features = [
    "async-await",
] }
mimxrt600-fcb = "0.2.0"
rand = { version = "0.8.5", default-features = false }
espi-service = { path = "../../espi-service", features = ["defmt"] }
embedded-services = { path = "../../embedded-service", features = ["defmt"] }

embedded-batteries-async = { version = "0.2.0", features = ["defmt"] }
bq25773 = { git = "https://github.com/OpenDevicePartnership/bq25773" }
battery-service = { path = "../../battery-service", features = ["defmt"] }
bq40z50-rx = { version = "0.1", features = ["r5"] }
static_cell = "2.1.0"
embassy-embedded-hal = { version = "0.5.0", default-features = false }

# Needed otherwise cargo will pull from git
[patch."https://github.com/OpenDevicePartnership/embedded-services"]
embedded-services = { path = "../../embedded-service" }
